use nhl_api::GameDate;
use std::sync::Arc;
use std::time::{Duration, SystemTime};
use tracing::debug;

use super::action::Action;
use super::component::Effect;
use super::component_store::ComponentStateStore;
use super::state::{AppState, SystemState};
use super::types::StackedDocument;

/// Format GameDate for breadcrumb display (MM/DD)
pub(crate) fn format_date_for_breadcrumb(date: &GameDate) -> String {
    match date {
        GameDate::Date(naive_date) => naive_date.format("%m/%d").to_string(),
        GameDate::Now => chrono::Local::now()
            .date_naive()
            .format("%m/%d")
            .to_string(),
    }
}

// Import sub-reducers from the parent framework module
use crate::tui::reducers::{
    rebuild_standings_focusable_metadata, reduce_data_loading, reduce_document_stack,
    reduce_navigation, reduce_settings,
};

/// Returns true when enough time has passed since the last data refresh to
/// warrant triggering another one, based on the configured `refresh_interval`.
///
/// Returns false if no refresh has happened yet (still loading initial data)
/// or if the system clock reports the last refresh as being in the future.
fn should_auto_refresh(system: &SystemState) -> bool {
    match system.last_refresh {
        Some(last_refresh) => {
            let interval = Duration::from_secs(system.config.refresh_interval as u64);
            match SystemTime::now().duration_since(last_refresh) {
                Ok(elapsed) => elapsed >= interval,
                Err(_) => false,
            }
        }
        None => false,
    }
}

/// Scores: SelectGame pushes a boxscore document onto the stack.
///
/// Looks up the game's team abbrevs and scores from the current schedule (falling back to
/// placeholders if not yet loaded) and delegates to `reduce_document_stack` to push the document.
fn handle_select_game(state: AppState, game_id: i64) -> (AppState, Effect) {
    // Format the current date for breadcrumb display
    let game_date = format_date_for_breadcrumb(&state.ui.scores.game_date);

    // Look up game data from schedule to get team abbrevs and scores
    let (away_abbrev, home_abbrev, away_score, home_score) =
        if let Some(schedule) = &*state.data.schedule {
            schedule
                .games
                .iter()
                .find(|g| g.id == game_id.into())
                .map(|g| {
                    (
                        g.away_team.abbrev.clone(),
                        g.home_team.abbrev.clone(),
                        g.away_team.score.unwrap_or(0),
                        g.home_team.score.unwrap_or(0),
                    )
                })
                .unwrap_or_else(|| ("???".to_string(), "???".to_string(), 0, 0))
        } else {
            ("???".to_string(), "???".to_string(), 0, 0)
        };

    reduce_document_stack(
        state,
        &Action::PushDocument(StackedDocument::Boxscore {
            game_id,
            away_abbrev,
            home_abbrev,
            away_score,
            home_score,
            game_date,
        }),
    )
    .unwrap_or_else(|s| (s, Effect::None))
}

/// Scores: switch the active game date and clear the stale schedule/game data so the
/// fetch effect (generated by Runtime::dispatch after calling this reducer) populates
/// fresh state instead of momentarily showing the previous date's data under the new one.
fn handle_refresh_schedule(state: AppState, date: GameDate) -> (AppState, Effect) {
    let mut new_state = state;
    new_state.ui.scores.game_date = date;
    new_state.data.schedule = Arc::new(None);
    Arc::make_mut(&mut new_state.data.game_info).clear();
    Arc::make_mut(&mut new_state.data.period_scores).clear();
    (new_state, Effect::None)
}

fn handle_update_terminal_width(state: AppState, width: u16) -> (AppState, Effect) {
    let mut new_state = state;
    new_state.system.terminal_width = width;
    (new_state, Effect::None)
}

/// Standings: rebuild focusable metadata after a view change (e.g. team order toggle).
/// The metadata lives in component state, not `AppState`, so this doesn't mutate `state`.
fn handle_rebuild_standings_focusable(
    state: AppState,
    component_states: &mut ComponentStateStore,
) -> (AppState, Effect) {
    rebuild_standings_focusable_metadata(&state, component_states);
    (state, Effect::None)
}

/// Dispatches a `ComponentMessage` action to the addressed component's local state.
fn handle_component_message(
    state: AppState,
    path: &str,
    message: &dyn crate::tui::action::ComponentMessageTrait,
    component_states: &mut ComponentStateStore,
) -> (AppState, Effect) {
    if let Some(component_state) = component_states.get_mut_any(path) {
        debug!("COMPONENT: Dispatching message to {}: {:?}", path, message);
        let effect = message.apply(component_state);
        (state, effect)
    } else {
        debug!("COMPONENT: No state found for path: {}", path);
        (state, Effect::None)
    }
}

/// Chains the shared-state sub-reducers (navigation, document stack, data loading),
/// passing state ownership through. Returns `Ok` from whichever sub-reducer handles the
/// action first, or `Err(state)` to let the caller fall through to tab-specific handling.
#[allow(clippy::result_large_err)]
fn try_sub_reducers(
    state: AppState,
    action: &Action,
    component_states: &mut ComponentStateStore,
) -> Result<(AppState, Effect), AppState> {
    let state = match reduce_navigation(state, action, component_states) {
        Ok(result) => return Ok(result),
        Err(state) => state,
    };
    let state = match reduce_document_stack(state, action) {
        Ok(result) => return Ok(result),
        Err(state) => state,
    };
    reduce_data_loading(state, action, component_states)
}

fn handle_set_status_message(
    state: AppState,
    message: String,
    is_error: bool,
) -> (AppState, Effect) {
    let mut new_state = state;
    if is_error {
        new_state.system.set_status_error_message(message);
    } else {
        new_state.system.set_status_message(message);
    }
    (new_state, Effect::None)
}

/// Advances the loading animation frame and, once the configured refresh interval has
/// elapsed, triggers a data refresh.
fn handle_tick(state: AppState) -> (AppState, Effect) {
    let mut new_state = state;
    // Wrap at 4 to match the 4-frame animation
    new_state.system.animation_frame = (new_state.system.animation_frame + 1) % 4;

    let effect = if should_auto_refresh(&new_state.system) {
        // Reset the timestamp immediately so subsequent ticks (before the
        // RefreshData round-trip completes) don't queue duplicate refreshes.
        new_state.system.last_refresh = Some(SystemTime::now());
        Effect::Action(Action::RefreshData)
    } else {
        Effect::None
    };

    (new_state, effect)
}

/// Pure state reducer - like Redux reducer
///
/// Takes current state, component state store, and an action, returns new state and optional effect.
/// This function is PURE - no side effects, no I/O, no async (except for component state updates).
/// All side effects are returned as `Effect` to be executed separately.
///
/// Note: component_states is passed as &mut to allow ComponentMessage actions to update
/// component-local state, but the reducer itself doesn't create side effects through this.
///
/// Ownership is passed through the sub-reducer chain to avoid cloning:
/// - Each sub-reducer returns Ok((state, effect)) if it handled the action
/// - Or Err(state) to pass ownership back for the next reducer to try
pub fn reduce(
    state: AppState,
    action: Action,
    component_states: &mut ComponentStateStore,
) -> (AppState, Effect) {
    // Component message dispatch (React-like component system)
    if let Action::ComponentMessage { path, message } = &action {
        return handle_component_message(state, path, message.as_ref(), component_states);
    }

    // Chain sub-reducers (navigation, document stack, data loading), passing ownership
    // through. Falls through to tab-specific action delegation below if none handled it.
    let state = match try_sub_reducers(state, &action, component_states) {
        Ok(result) => return result,
        Err(state) => state,
    };

    // Tab-specific action delegation
    match action {
        Action::SettingsAction(settings_action) => reduce_settings(state, settings_action),
        Action::SelectGame(game_id) => handle_select_game(state, game_id),
        Action::RefreshSchedule(date) => handle_refresh_schedule(state, date),
        Action::RebuildStandingsFocusable => {
            handle_rebuild_standings_focusable(state, component_states)
        }
        Action::SetStatusMessage { message, is_error } => {
            handle_set_status_message(state, message, is_error)
        }
        Action::UpdateTerminalWidth(width) => handle_update_terminal_width(state, width),
        Action::Tick => handle_tick(state),
        Action::Quit => (state, Effect::None),
        _ => (state, Effect::None),
    }
}

#[cfg(test)]
#[path = "reducer_tests.rs"]
mod tests;
